version: '3'
services:
  websocket:
    build:
      context: ./websocket
    container_name: websocket_container
    restart: always
    volumes:
      - ./ws_data:/app/ws_data
    command: bash start.sh
